Implement Capistrano
uclibs/treatment_database pull request #311
Opened 2022-06-09 15:02 UTC by bsp3ars

Adds capistrano support to the treatment database application. Also implements a systems config file for monitoring puma

2022-06-16 13:57 UTC, bsp3ars commented
In order to get the CircleCI build to pass, we will need to change the RAILS_MASTER_KEY in CircleCI in Project Settings > Environment Variables.

2022-06-16 16:09 UTC, hortongn commented
@bsp3ars The CircleCI problem is fixed.  CI was running the app in "test" mode like it should, but because the RAILS_MASTER_KEY variable had been added to the project settings the app was trying to use the (old) key even though it didn't need it.  So I just had to delete the master key from the CircleCI settings and the job then passed.

Can you please squash you commits and push up again?  I'll then review and merge.

2022-06-27 16:57 UTC, hortongn requested changes
@bsp3ars See my comments inline.  Also please squash your commits.  Thanks

2022-06-27 16:57 UTC, hortongn commented on config/deploy/production.rb
> +server 'libapps2.libraries.uc.edu', user: fetch(:username), password: fetch(:password), port: 22, roles: %i[web app db]
Change `libapps2.libraries.uc.edu` to `libapps.libraries.uc.edu`

2022-06-27 16:57 UTC, hortongn commented on Gemfile
> +  gem 'capistrano', '3.11.2'
Do we really need to be pinned to capistrano v3.11.2?

2022-06-29 21:02 UTC, hortongn approved these changes
@bsp3ars Well done.  Merging

2022-06-29 21:03 UTC, merged