WIP add csv export
uclibs/treatment_database pull request #390
Opened 2023-04-07 15:59 UTC by crowesn

2023-04-30 18:51 UTC, hortongn requested changes
@crowesn The CSV export works really well.  If Holly is happy with the fields in the CSV, then it's good.  Good job with ActiveStorage.  I do have a couple of inline comments and two more suggestions below:

On the /reports page, I suggest adding a note near the button that the export may take a minute to run.  When the report is ready, I suggest a flash message saying something like "Report 20230430T183918_export.csv is ready below."  If there's a long list of existing CSV files, it might not be apparent to the user that the file has shown up at the bottom of the list (especially if they have to scroll down).

We really do need to test export.rake.  Take a look at https://medium.com/@jelaniwoods/rspec-tests-for-rake-tasks-da7985896014

2023-04-30 18:51 UTC, hortongn commented on app/controllers/reports_controller.rb
> +    @reports = Report.all
Add a test for #index to your ReportsController spec.

2023-05-03 13:43 UTC, crowesn commented
@hortongn Updated branch deployed to libappstest.

2023-05-04 20:52 UTC, hortongn approved these changes
@crowesn Thanks for making the changes.  This is great work.  Merging

2023-05-04 20:52 UTC, merged