LIBTREATDB-56 Replace Devise with Custom Session Management - FEATURE BRANCH
uclibs/treatment_database pull request #532
Opened 2024-07-22 16:18 UTC by Janell-Huyck

https://ucdts.atlassian.net/browse/LIBTREATDB-56

## There are instructions for migrations and starting the app at the bottom of this description.

---

### Note to testers who have been working with other PR's
## Do not follow these instructions for testing this PR.  See the bottom of this PR description for instructions.

If you've been reviewing other PR's, you have likely had to run `rails db:migrate` for this one.  Now, if you're going back to that branch, your database is in a different state and you will be unable to run or test the program.  You will need to reset your databases.  Here is a simple way to do what is needed.  From your terminal, navigate to the branch you are reviewing, and then type (or copy/paste):

```
RAILS_ENV=development rails db:drop db:create db:schema:load db:seed
RAILS_ENV=test rails db:drop db:create db:schema:load db:seed
```

If you want to check things in the production environment, you would use the same line of commands for production:

```
RAILS_ENV=production rails db:drop db:create db:schema:load db:seed
```
--- 

### This PR removes Devise from Treatment Database and replaces it with custom sessions management. Devise touched many different areas of the app, so this is a large PR.

### Gem changes:
- Removes Devise
- Adds Bcrypt for handling password verification

### Routes changes
- remove Devise routes
- add sessions routes
- add admin/user_controller routes for admins to manage users
- limit "user" routes to functions normal users can do

### Controllers changes
- admin/users_controller
  - New controller, accessible only to admin accounts
  - used to create or edit any user account, (email, display name, password, active-status, role)
  - cannot delete an account
- users_controller
  - Updated, accessible to any user
  - update own display name (only)
  - cannot update own email , password, or username, in line with how Shibboleth will work
  - removed Devise-specific functionality now handled by admin/users_controller
- registration_controller
  - removed since this was a Devise-only controller
- sessions_controller
  - finds users
  - verifies active status and password checks
  - assigns session id's to the user ids
  - destroys sessions
- front_controller (shows the home page & is the space to login)
  - set it so we aren't validating login status when visiting this page
- concern: authentication
  - included in application_controller
  - doesn't allow the user to visit any pages if not logged in and active

### Helpers changes
- new helper: navigation_helper
  - shows one of two navigation bars based on user's login status
  - determines what links will be shown to the user based on their CanCan permissions

### Mailers
- Removes application_mailer.rb. This was a Devise mailer, and we do not anticipate needing to email users for anything in the future since password issues will be handled through Shibboleth.

### Models
- CanCan Ability (model):
  - New User Permissions: For both 'standard' and 'read_only' roles, new permissions were added. Users can now:
    - Read and update their own User record
    - They are also explicitly forbidden from accessing the index action on the User model
- Users Model
  - Adds new validations:
    - email: 
      - must end in @uc.edu or @ucmail.uc.edu
      - must be unique
      - must be present
    - display name: 
      - can only contain alphanumeric characters and space, period, dash, or underscore. 
      - must be present
      - must be unique
      - max-length 30 characters.
    - username: 
      - can only contain alphanumeric characters, period, dash, or underscore (no space). 
      - must be unique 
      - must be present.
    - role: must be present, must be included in a frozen list
  - "activate_new_account" and "default_role" logic now part of admin_users model & controller
  - "active_for_authentication" logic now part of authentication concern

### Views changes
- admin user functionalities
  - only viewable by admin users
  - new: "_form" for creating or editing a new user
    - (This will need to be updated to not include password once Shibboleth is working. [LIBTREATDB-83](https://ucdts.atlassian.net/browse/LIBTREATDB-83))
  - "edit" wrapper for "_form" for editing user
  - "new" wrapper for "_form" for creating user
    - (This will need to be updated to not include password once Shibboleth is working. [LIBTREATDB-83](https://ucdts.atlassian.net/browse/LIBTREATDB-83))
  - "index" - removed unnecessary permission check, updated link to edit & create
- removed Devise views
- navbar: updated links
- sessions: new login page since Devise view isn't being used
- regular users: updated to only pertain to users updating their own display name and viewing email and role

### Config changes
- config/environments/test.rb: remove reference to Devise
- Devise initializers: removed

### Routes
- reconfigued users and admin/users routes to align with new functionality
- added sessions routes
- removed Devise routes

### Migrations
- remove devise-specific user fields
- add column "username" to users and fills in current data with default username
- adds new column constraints to users email, username, display name, role, account_active, and password_digest

### Seeds
- updates the seeded emails to all be @uc.edu

### Tests
The changes to testing are significant since Devise was used in all tests that required logging in or authentication. A few highlights:

- New helpers
  - controller, request, view, system authentication helpers stub logging in and authorization for their respective tests
  - spec/support/shoulda_matchers.rb - initializing shoulda matches used in abbreviated_treatment_report_spec.rb
- Changes to controller tests
  - Added sessions_controller tests
  - Remove Devise helpers and replace with custom helpers (above)
  - New tests for admin-specific user functionality
  - spec/controllers/users_controller_spec.rb - modified to only test functionality available to non-admins since admin functionality is now in spec/controllers/admin_users_controller_spec.rb
- New view tests:
  - Split navigation view tests into logged_in and logged_out tests
- Changes to factories
  - abbreviated_treatment_report: if not already associated with a conservation record, will create one and associate with it.
  - reports: it used to reference a non-existent file. Created a file and placed in "fixtures"
  - users:  
    - Introduces a transient attribute n using a custom sequence user_sequence. This stores the sequence value and is used for generating the username, email, and display_name fields.
    - New Fields:
      - password_confirmation: Added to match the password for cases where password confirmation is required.
      - username: Added and generated using the transient attribute n and timestamp, ensuring a unique username for each user.
    - The email domain was updated from example.com to uc.edu.
- Remove Devise-specific tests
  - spec/mailers/application_mailer_spec.rb
  - spec/mailers/devise_mailer_spec.rb
- Model tests
  - spec/models/ability_spec.rb - refactored to allow easier maintenance

### Spec helper
- Removed Devise setup

## Things to test:

### Before running rails db:migrate:
<h2>IMPORTANT</h2>
<h3>Prepare your database</h3>
You probably have some seeded or old data that will break the app and needs to be fixed BEFORE you run migrations.  The user emails now MUST end in @uc.edu or @ucmail.uc.edu.  You can update this via `rails console` or from within the app.  The easiest way is probably through the app, like this: 

- Load up the qa branch and log in as an admin.  (chuck@chuck.codes, password 'notapass' is a default user)
- Navigate to the "Users" menu and for each of your users update the email domain to be @uc.edu or @ucmail.uc.edu. 

You will want to check that running the migrations doesn't destroy the data already in the user's database.
- Navigate to the Conservation Records page and change something that you can recognize a [...]

2024-08-26 20:05 UTC, hortongn commented
Suggested strategy for reviewing this PR:
1. A couple people get this running in their local environments and do an end-to-end manual test of the app.  Verify all behavior as best as possible.  Verify existing data is unaltered.
2. After any needed changes are made, do a code review on this.
3. Deploy to libappstest and do another run-through of the app.

2024-09-05 20:46 UTC, hortongn requested changes
@Janell-Huyck I added some inline comments about test coverage, but other than that I everything else looks good.  I found no problems running the app.

2024-09-05 20:46 UTC, hortongn commented on app/controllers/sessions_controller.rb
> +    redirect_to root_path, notice: 'Logged out successfully'
I see you have a controller test for #destroy, but Coveralls is saying that the two lines in your destroy method are not covered for some reason.

2024-09-05 20:46 UTC, hortongn commented on app/controllers/sessions_controller.rb
> +      handle_invalid_credentials
`handle_invalid_credentials` is untested

2024-09-05 20:46 UTC, hortongn commented on app/controllers/admin/users_controller.rb
> +      redirect_to admin_users_path, alert: 'User deletion is not permitted.'
#destroy doesn't have a test.

2024-09-05 20:46 UTC, hortongn commented on app/controllers/admin/users_controller.rb
> +        render :edit
This else condition is untested.

2024-09-05 20:46 UTC, hortongn commented on app/controllers/concerns/.keep
Do we need this .keep file?

2024-09-09 17:17 UTC, scherztc commented
I ran through the Manuel Test Script for each role and the only confusing thing for me was the User Edit screen as Admin.

I was confused on whether I needed to type in the Admin password to make the changes or whether or not I was changing the users password.   This confusion needs to be cleared up.

Also, How does a user change their own password?

<img width="1185" alt="Screenshot 2024-09-09 at 1 10 50 PM" src="https://github.com/user-attachments/assets/7a421be5-401f-4203-80c6-5ccacb816da4">

2024-09-10 18:02 UTC, scherztc approved these changes

2024-09-12 15:04 UTC, merged